### ISSUE TITLE
5'Flank not being rendered

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/oncotator#315]
@alexramos Can you please provide more test cases (besides the one below)?

7 55086709 55086709 T C

Thanks to @erheinbay for finding this.

**Comment by alexramos** [comment]
7 55086709 55086709 T C # 5'Flank EGFR (+ strand tx) mutation
5 1295165 1295165 A T # 5'Flank TERT (- strand tx) mutation

**Comment by LeeTL1220** [comment]
@alexramos Can we clsoe this issue?

**Comment by alexramos** [comment]
yes
