### ISSUE TITLE
Oncotator input VCF REF/ALT alleles do not match output alleles

### ISSUE THREAD

**Issue by jhl667** [broadinstitute/oncotator#340]
We ran across this issue working with a bare bones input VCF (CHROM, POS, ALT, and REF only, the rest '.').  For instance:

1	162740326	.	GT	C	.	.	.

results in:

1	162740326	.	CT	C	.

Similar behavior for C/TCT which becomes C/CCT.  All of the examples of this behavior I have found to this point are indels.

**Comment by dwking2000** [comment]
the version of Oncotator we are running shows up in the output file as:

##oncotator_version=Oncotator_v1.8.0.0_|_Flat_File_Reference_hg19_|_GENCODE_v19_CANONICAL_|_UniProt_AAxform_2014_12_|_COSMIC_v62_291112_|_dbNSFP_v2.4_|_1000gp3_20130502_|_dbSNP_build_142_|_ESP_6500SI-V2_|_ESP_6500SI-V2_|_ClinVar_12.03.20_|_UniProt_AA_2014_12_|_CCLE_By_GP_09292010_|_ORegAnno_UCSC_Track_|_Ensembl_ICGC_MUCOPA_|_TCGAScape_110405_|_HGNC_Sept172014_|_MutSig_Published_Results_20110905_|_Familial_Cancer_Genes_20110905_|_CCLE_By_Gene_09292010_|_gencode_xref_refseq_metadata_v19_|_HumanDNARepairGenes_20110905_|_COSMIC_FusionGenes_v62_291112_|_UniProt_2014_12_|_COSMIC_Tissue_291112_|_TUMORScape_20100104_|_CGC_full_2012-03-15_|_ACHILLES_Lineage_Results_110303_

**Comment by LeeTL1220** [comment]
Is this on the website or the standalone?

On Fri, Feb 12, 2016 at 5:26 PM, Doug King <notifications@github.com> wrote:

> the version of Oncotator we are running shows up in the output file as:
>
> ##oncotator_version=Oncotator_v1.8.0.0_|*Flat_File_Reference_hg19*|
> *GENCODE_v19_CANONICAL*|*UniProt_AAxform_2014_12*|*COSMIC_v62_291112*|
> *dbNSFP_v2.4*|*1000gp3_20130502*|*dbSNP_build_142*|*ESP_6500SI-V2*|
> *ESP_6500SI-V2*|*ClinVar_12.03.20*|*UniProt_AA_2014_12*|
> *CCLE_By_GP_09292010*|*ORegAnno_UCSC_Track*|*Ensembl_ICGC_MUCOPA*|
> *TCGAScape_110405*|*HGNC_Sept172014*|*MutSig_Published_Results_20110905*|
> *Familial_Cancer_Genes_20110905*|*CCLE_By_Gene_09292010*|
> *gencode_xref_refseq_metadata_v19*|*HumanDNARepairGenes_20110905*|
> *COSMIC_FusionGenes_v62_291112*|*UniProt_2014_12*|*COSMIC_Tissue_291112*|
> *TUMORScape_20100104*|*CGC_full_2012-03-15*|
> *ACHILLES_Lineage_Results_110303*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/oncotator/issues/340#issuecomment-183510923>
> .
>



-- 
Lee Lichtenstein
Broad Institute
75 Ames Street, Room 7003EB
Cambridge, MA 02142
617 714 8632

**Comment by dwking2000** [comment]
Standalone

**Comment by LeeTL1220** [comment]
what you've shown there is not a valid VCF.  The ref and alt must start
with the reference base before the actual mutation.  Oncotator is putting
the reference base as a prepend, which is correct.

**Comment by jhl667** [comment]
@LeeTL1220 Ah, yes, I overlooked that.  I will have to bring this back to the developers of this particular variant caller.

I would say that changing GT/C to CT/C does not completely make sense.  If you look at the reference, the base immediately preceding GT is G (AGG**GT**GT).  So, you would write this as GGT/GC, certainly not CT/C.  I understand that Oncotator is assuming the input VCF follows the spec, but I would think some quick validation should occur before modifying these fields and potentially grabbing incorrect annotations.

**Comment by dwking2000** [comment]
You can close this issue, we have determined the input VCF is not valid.  It would be good to open another issue that addresses Oncotator allowing invalid data to be processed.
