### ISSUE TITLE
COSMIC wrong annotation

### ISSUE THREAD

**Issue by romagnolid** [broadinstitute/oncotator#374]
I noticed that some variants are annotated with COSMIC regardless of the protein change.
I wonder if that's an expected behaviour.

Hugo_Symbol |Protein_Change |COSMIC_overlapping_mutations                                                                                                                         
-----------|--------------|----------------------------                                                                                                                   
FANCL       |p.F36L         |p.F36F(1)

**Comment by LeeTL1220** [comment]
When the tool was originally designed, the users wanted anything that overlapped.  So this is by design.

**Comment by romagnolid** [comment]
Thanks for the clarification.
